Optional removal of node taint on successful IP assignment
doitintl/kubeip pull request #146
Opened 2024-05-07 18:24 UTC by RagnarHal

This PR adds a feature that allows removal of a node taint upon a successful IP address assignment. Using this should avoid potential race conditions where workloads may be scheduled on newly provisioned nodes before KubeIP has completed the IP assignment. I have tested this on a GKE cluster, but not in AWS. There shouldn't be anything vendor-specific here.

The specific use case we have for this is that we run some jobs on elastic node pools, which call services with IP-whitelisting. We had observed that in rare cases, it would take a while (up to a minute) for the nodes to receive their IP addresses, and meanwhile workloads were free to be scheduled on the nodes. We wanted to ensure that calls to these services were not made before the node had received a static IP address.

This should be backwards-compatible with current deployments of KubeIP, and if the feature is not enabled then it should behave exactly as it does currently.

Using this feature requires an additional, potentially sensitive permission on the ClusterRole. This is explained in the readme, but not using the feature (i.e. not explicitly setting the `taint-key` configuration option) does not require any additional permissions, and it will still work with only the "get" permission.

2024-05-08 13:31 UTC, alexei-led approved these changes
@RagnarHal LGTM thank you for this PR. Reasonable use case.

2024-05-08 13:47 UTC, alexei-led requested changes

2024-05-08 13:47 UTC, alexei-led commented on cmd/main.go
@RagnarHal suppress linter warning (contextcheck)

```
if releaseErr := releaseIP(assigner, n); releaseErr != nil { //nolint:contextcheck
```

2024-05-10 15:24 UTC, RagnarHal commented on cmd/main.go
Thanks, fixed.

2024-05-13 09:00 UTC, merged